version: "2"
services:
  web:
    build: .
    ports:
      - "3020:3020"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: "mongodb://127.0.0.1:27017/population_census"
  mongo:
    image: mongo
    command: mongod --smallfiles
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"